apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaled-object
  namespace: default
spec:
  scaleTargetRef:
    name: cron-demo-app
  pollingInterval: 10
  cooldownPeriod: 10
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: cron
      metadata:
        timezone: Asia/Kolkata
        start: "16 12 * * *"
        end: "19 12 * * *"
        desiredReplicas: "2"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaled-object1
  namespace: default
spec:
  scaleTargetRef:
    name: frontend
  pollingInterval: 10
  cooldownPeriod: 10
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: cron
      metadata:
        timezone: Asia/Kolkata
        start: "59 12 * * *"
        end: "03 13 * * *"
        desiredReplicas: "2"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
