apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaled-object
  namespace: default
spec:
  scaleTargetRef:
    name: cron-demo-app
  pollingInterval: 10
  cooldownPeriod: 10
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: cron
      metadata:
        timezone: Asia/Kolkata
        start: "16 12 * * *"
        end: "19 12 * * *"
        desiredReplicas: "2"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaled-object1
  namespace: default
spec:
  scaleTargetRef:
    name: frontend  # Targets the frontend Deployment for scaling
  pollingInterval: 10 # KEDA checks cron schedule every 10 seconds (default: 30s)
  cooldownPeriod: 10 # After cron ends, wait 10s before signaling scale-down (default: 300s)
  minReplicaCount: 0 # Scales down to 0 pods when cron is inactive
  maxReplicaCount: 5 # Hard cap: never scale beyond 5 pods
  triggers:
    - type: cron
      metadata:
        timezone: Asia/Kolkata
        start: "44 17 * * *"
        end: "46 17 * * *"
        desiredReplicas: "2"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10 # HPA reacts within 10s of KEDA's signal
